name: Publish snapshot package to GitHub Packages
on:
 push:
  branches:
   - master

jobs:
 publish:
  runs-on: ubuntu-latest
  permissions:
   contents: read
   packages: write
  steps:
   - uses: actions/checkout@v4
   - uses: actions/setup-java@v3
     with:
      java-version: '11'
      distribution: 'temurin'
   - name: Setup Gradle
     uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
   - name: run version
     run: |
      echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
      echo "Tag name from github.ref_name: ${{  github.ref_name }}"
   - name: Publish package
     run: gradle publish
     env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
